CREATE TABLE scores(
    score_id NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOCACHE,
    score NUMBER(2),
    game_id NUMBER(6),
    user_id NUMBER(6)
);

ALTER TABLE scores ADD(
    CONSTRAINT game_id_for_score_fk FOREIGN KEY(game_id) REFERENCES video_games(game_id),
    CONSTRAINT user_id_for_score_fk FOREIGN KEY(user_id) REFERENCES users(user_id)
);

commit;