CREATE TABLE user_image_table(
    image_id NUMBER(6) GENERATED BY DEFAULT ON NULL AS IDENTITY NOCACHE,
    data BLOB,
    image_name VARCHAR2(120) CONSTRAINT user_image_name_nn NOT NULL,
    image_type VARCHAR2(120) CONSTRAINT user_image_type_nn NOT NULL,
    user_id NUMBER(6)
);

ALTER TABLE user_image_table ADD(
    CONSTRAINT user_image_id_pk PRIMARY KEY(image_id),
    CONSTRAINT user_id_for_image_fk FOREIGN KEY(user_id) REFERENCES users(USER_ID)
);