CREATE TABLE my_game_list_config(
     config_id NUMBER(6) GENERATED BY DEFAULT ON NULL AS IDENTITY NOCACHE,
     background_color VARCHAR2(120),
     text_color VARCHAR2(120),
     user_id NUMBER(6)
);

ALTER TABLE my_game_list_config ADD(
    CONSTRAINT game_list_config_id_pk PRIMARY KEY(config_id),
    CONSTRAINT user_id_for_game_list_config_fk FOREIGN KEY(user_id) REFERENCES users(USER_ID)
);