CREATE TABLE game_list_status(
   status_id NUMBER(6) GENERATED BY DEFAULT ON NULL AS IDENTITY NOCACHE,
   status_name VARCHAR2(100) CONSTRAINT status_name_nn NOT NULL
);

ALTER TABLE game_list_status ADD(
    CONSTRAINT status_id_pk PRIMARY KEY(status_id)
);