CREATE TABLE image_table(
    image_id NUMBER(6) GENERATED BY DEFAULT ON NULL AS IDENTITY NOCACHE,
    data BLOB,
    image_name VARCHAR2(120) CONSTRAINT image_name_nn NOT NULL,
    image_type VARCHAR2(120) CONSTRAINT image_type_nn NOT NULL,
    game_id NUMBER(6)
);

ALTER TABLE image_table ADD(
    CONSTRAINT image_id_pk PRIMARY KEY(image_id),
    CONSTRAINT game_id_fk FOREIGN KEY(game_id) REFERENCES video_games(game_id)
);