CREATE TABLE requests(
    request_id NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOCACHE,
    game_name VARCHAR2(1000),
    link VARCHAR2(4000),
    details VARCHAR2(4000),
    user_id NUMBER(6),
    created_at TIMESTAMP(6)
);

ALTER TABLE requests ADD(
    CONSTRAINT constraint_user_id_for_request_fk FOREIGN KEY(user_id) REFERENCES users(user_id)
);

commit;